//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task_4_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int RegisterID { get; set; }
        public int RegisterInventoryNumber { get; set; }
        public int RegisterLibraryCardNumber { get; set; }
        public System.DateTime RegisterDateIssue { get; set; }
        public System.DateTime RegisterPlannedDateReturn { get; set; }
        public Nullable<System.DateTime> RegisterActualDateReturn { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
